### ISSUE TITLE
TVM problem for Android

### ISSUE THREAD

**Issue by robo-z** [microsoft/T-MAC#51]
I can perform normal inference using pre-built kernels. I want to compile a kernel for llama3-8b-4bit, but I encounter the following error. I would like to know what the problem is.

system:ubuntu-24.04
Additionally, I run it on Ubuntu without encountering any errors.

```
(tmac) david@David:~/code/T-MAC$ python tools/run_pipeline.py -o /media/david/data1/models/ChenMnZ/Llama-3-8b-instruct-EfficientQAT-w4g128-GPTQ/ -m llama-3-8b-4bit -d android -ndk $NDK_HOME -dt
Running STEP.0: Compile kernels
  Running command in /home/david/code/T-MAC/deploy:
    python compile.py -o tuned -da -nt 4 -tb -gc -gs 128 -ags 64 -m llama-3-8b-4bit -md /media/david/data1/models/ChenMnZ/Llama-3-8b-instruct-EfficientQAT-w4g128-GPTQ/ -d android
Please check logs/2024-09-25-16-56-45.log for what's wrong
(tmac) david@David:~/code/T-MAC$ cat logs/2024-09-25-16-56-45.log
Cannot find config for target=llvm -keys=arm_cpu,cpu -device=arm_cpu -mattr=+v8.2a,+fullfp16,+fp-armv8,+neon -mtriple=aarch64-linux-gnu, workload=('qgemm_lut_t4_int8_m16384_k4096_n1_b4', 16384, 1, 4096). A fallback configuration is used, which may bring great performance regression.
Traceback (most recent call last):
  File "/home/david/code/T-MAC/deploy/compile.py", line 240, in <module>
    main()
  File "/home/david/code/T-MAC/deploy/compile.py", line 230, in main
    compile(**device_kwargs)
  File "/home/david/code/T-MAC/deploy/compile.py", line 126, in compile
    qgemm_mod = qgemm_lut.compile(
                ^^^^^^^^^^^^^^^^^^
  File "/home/david/code/T-MAC/python/t_mac/ops/base.py", line 268, in compile
    func = tvm.build(s, tensors, name=template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/code/T-MAC/3rdparty/tvm/python/tvm/driver/build_module.py", line 297, in build
    rt_mod_host = _driver_ffi.tir_to_runtime(annotated_mods, target_host)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/code/T-MAC/3rdparty/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "/home/david/code/T-MAC/3rdparty/tvm/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm._ffi.base.TVMError: Traceback (most recent call last):
  161: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::runtime::Module (tvm::runtime::Map<tvm::Target, tvm::IRModule, void, void> const&, tvm::Target)>::AssignTypedLambda<tvm::__mk_TVM24::{lambda(tvm::runtime::Map<tvm::Target, tvm::IRModule, void, void> const&, tvm::Target)#1}>(tvm::__mk_TVM24::{lambda(tvm::runtime::Map<tvm::Target, tvm::IRModule, void, void> const&, tvm::Target)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  160: tvm::TIRToRuntime(tvm::runtime::Map<tvm::Target, tvm::IRModule, void, void> const&, tvm::Target const&)
  159: tvm::codegen::Build(tvm::IRModule, tvm::Target)
  158: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::runtime::Module (tvm::IRModule, tvm::Target)>::AssignTypedLambda<tvm::codegen::__mk_TVM0::{lambda(tvm::IRModule, tvm::Target)#1}>(tvm::codegen::__mk_TVM0::{lambda(tvm::IRModule, tvm::Target)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  157: tvm::codegen::LLVMModuleNode::Init(tvm::IRModule const&, tvm::Target const&)
  156: tvm::codegen::CodeGenCPU::AddFunction(tvm::GlobalVar const&, tvm::tir::PrimFunc const&)
  155: tvm::codegen::CodeGenLLVM::AddFunctionInternal(tvm::GlobalVar const&, tvm::tir::PrimFunc const&)
 ...
  12: tvm::codegen::CodeGenLLVM::VisitStmt_(tvm::tir::SeqStmtNode const*)
  11: tvm::codegen::CodeGenAArch64::VisitStmt_(tvm::tir::AttrStmtNode const*)
  10: tvm::codegen::CodeGenCPU::CreateComputeScope(tvm::tir::AttrStmtNode const*)
  9: tvm::codegen::CodeGenCPU::VisitStmt_(tvm::tir::ForNode const*)
  8: tvm::codegen::CodeGenCPU::CreateParallelLaunch(tvm::tir::Stmt const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
  7: tvm::codegen::CodeGenCPU::VisitStmt_(tvm::tir::ForNode const*)
  6: tvm::codegen::CodeGenLLVM::CreateSerialFor(llvm::Value*, llvm::Value*, llvm::Value*, tvm::tir::Var const&, tvm::tir::Stmt const&)
  5: tvm::codegen::CodeGenLLVM::VisitStmt_(tvm::tir::SeqStmtNode const*)
  4: tvm::codegen::CodeGenAArch64::VisitStmt_(tvm::tir::AttrStmtNode const*)
  3: tvm::codegen::CodeGenCPU::VisitStmt_(tvm::tir::AttrStmtNode const*)
  2: tvm::codegen::CodeGenLLVM::HandleImport(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  1: tvm::codegen::LLVMInstance::ParseIR(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
  0: tvm::codegen::LLVMInstance::ParseBuffer(llvm::MemoryBuffer const&) const
  %42 = zext nneg i32 %41 to i64
             ^
  File "/home/david/code/T-MAC/3rdparty/tvm/src/target/llvm/llvm_instance.cc", line 176
error: expected type
(tmac) david@David:~/code/T-MAC$ 

```

**Comment by kaleid-liner** [comment]
I have encountered such errors due to mismatched llvm/clang version between TVM build and runtime. Can you check if you are using the clang the scripts downloaded for you? `python -c "import t_mac; print(t_mac.__version__); from tvm.contrib.clang import find_clang; print(find_clang())"` should return `/home/David/code/T-MAC/build/clang+llvm...` and `llvm-config --version` should return `17.0.6`.

**Comment by robo-z** [comment]
> I have encountered such errors due to mismatched llvm/clang version between TVM build and runtime. Can you check if you are using the clang the scripts downloaded for you? `python -c "import t_mac; print(t_mac.__version__); from tvm.contrib.clang import find_clang; print(find_clang())"` should return `/home/David/code/T-MAC/build/clang+llvm...` and `llvm-config --version` should return `17.0.6`.

Thank you for your reply. After executing the above command, the output is as follows:
```
(tmac) david@David:~/code/T-MAC$ python -c "import t_mac; print(t_mac.__version__); from tvm.contrib.clang import find_clang; print(find_clang())"
1.0.0a3
['/home/david/code/T-MAC/build/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/bin/clang-17', '/home/david/code/T-MAC/build/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/bin/clang']
(tmac) david@David:~/code/T-MAC$ llvm-config --version
17.0.6
```
However, I've noticed that this `clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04`does not match my system (ubuntu 24.04), and I'm wondering if it could have an impact.
This mismatch does not affect the compilation and inference of T-MAC on the Ubuntu system.
The problem only occurs when cross-compiling for Android.

**Comment by kaleid-liner** [comment]
@robo-z Yes, this mismatch won't have any impact.

> The problem only occurs when cross-compiling for Android.

In this case, the reason could be related to `export TVM_NDK_CC=/opt/android-toolchain-arm64/bin/clang++` in android.md. Can you check the version of the clang of android toolchain? You may need to download a newer Android NDK. From my experience, it need to be >= 15 and < 18. Let me check my android NDK version and inform you later.

**Comment by robo-z** [comment]
Yes, I installed two versions of the NDK, one being version 21 and the other version 27, with corresponding clang++ versions of 9 and 18, perfectly avoiding the matching interval. I then installed NDK version 26, which corresponds to clang++ version 17, and now I am able to cross-compile.

Thank you very much!

**Comment by kaleid-liner** [comment]
Great. I will add the ndk version requirement to the doc.
