### ISSUE TITLE
Andorid tune kernel question

### ISSUE THREAD

**Issue by qw1319** [microsoft/T-MAC#53]
when i tune kernel on andorid，accoding to `docs/andoid.md   :   python -m tvm.exec.rpc_tracker`;
But i meet this question:`root@a23bc1a1da28:/home/merge_tmac/T-MAC# python -m tvm.exec.rpc_tracker
2024-09-26 13:39:49.926 INFO bind to 0.0.0.0:9190`

**Comment by qw1319** [comment]
when i run `python -m tvm.exec.query_rpc_tracker`
 i meet this question

`Tracker address 127.0.0.1:9190

Server List
------------------------------
server-address           key
------------------------------
------------------------------

Queue Status
---------------------------
key   total  free  pending
---------------------------
---------------------------`

**Comment by kaleid-liner** [comment]
You need to make sure your phone and host pc are in the same network, and if you have already checked it, the most possible cause is your firewall blocking incoming connections. A simple solution is to close your firewall.

**Comment by qw1319** [comment]
> You need to make sure your phone and host pc are in the same network, and if you have already checked it, the most possible cause is your firewall blocking incoming connections. A simple solution is to close your firewall.

my firewall is closed & my phone and pc in the same network. do u have any method？

**Comment by qw1319** [comment]
> > You need to make sure your phone and host pc are in the same network, and if you have already checked it, the most possible cause is your firewall blocking incoming connections. A simple solution is to close your firewall.
> 
> my firewall is closed & my phone and pc in the same network. do u have any method？

when i run python -m tvm.exec.query_rpc_tracker
i meet this question

`Tracker address 127.0.0.1:9190
this is not same as `docs/android.md`
![image](https://github.com/user-attachments/assets/6543f64b-9967-465e-82b2-19da28d855d0)

**Comment by qw1319** [comment]
> > > You need to make sure your phone and host pc are in the same network, and if you have already checked it, the most possible cause is your firewall blocking incoming connections. A simple solution is to close your firewall.
> > 
> > 
> > my firewall is closed & my phone and pc in the same network. do u have any method？
> 
> when i run python -m tvm.exec.query_rpc_tracker i meet this question
> 
> `Tracker address 127.0.0.1:9190` this is not same as `docs/android.md` ![image](https://private-user-images.githubusercontent.com/35762142/371133859-6543f64b-9967-465e-82b2-19da28d855d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNTI3MTEsIm5iZiI6MTcyNzM1MjQxMSwicGF0aCI6Ii8zNTc2MjE0Mi8zNzExMzM4NTktNjU0M2Y2NGItOTk2Ny00NjVlLTgyYjItMTlkYTI4ZDg1NWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDEyMDY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0OGIyYzdlOGM1Mzk1YzYxMGI3OGJkMWQ3NTViOGQ1MDQ3MzhjYjE5ZWM5ZTFlZTkzZjk4N2ZlY2U1NDQyNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1aUh6FjZbDON8gv8h8wH48ceMWoaQZ1i6BcD9_s9sHY)

**Comment by qw1319** [comment]
i  run cmd `python3 ../../T-MAC/3rdparty/tvm/apps/android_rpc/tests/android_rpc_test.py`
but get error 
`2024-09-27 10:14:14.996 WARNING Cannot connect to tracker ('0.0.0.0', 9190), retry in 5 secs...
2024-09-27 10:14:20.002 WARNING Cannot connect to tracker ('0.0.0.0', 9190), retry in 5 secs...
Traceback (most recent call last):
  File "/home/alexjiao/T-MAC/3rdparty/tvm/python/tvm/rpc/base.py", line 188, in connect_with_retry
    sock.connect(addr)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexjiao/merge_tmac/T-MAC/../../T-MAC/3rdparty/tvm/apps/android_rpc/tests/android_rpc_test.py", line 129, in <module>
    test_rpc_module()
  File "/home/alexjiao/merge_tmac/T-MAC/../../T-MAC/3rdparty/tvm/apps/android_rpc/tests/android_rpc_test.py", line 56, in test_rpc_module
    tracker = rpc.connect_tracker(tracker_host, tracker_port)
  File "/home/alexjiao/T-MAC/3rdparty/tvm/python/tvm/rpc/client.py", line 558, in connect_tracker
    return TrackerSession((url, port))
  File "/home/alexjiao/T-MAC/3rdparty/tvm/python/tvm/rpc/client.py", line 312, in __init__
    self._connect()
  File "/home/alexjiao/T-MAC/3rdparty/tvm/python/tvm/rpc/client.py", line 318, in _connect
    self._sock = base.connect_with_retry(self._addr)
  File "/home/alexjiao/T-MAC/3rdparty/tvm/python/tvm/rpc/base.py", line 195, in connect_with_retry
    raise RuntimeError(f"Failed to connect to server {str(addr)}")
RuntimeError: Failed to connect to server ('0.0.0.0', 9190)
`

**Comment by qw1319** [comment]
after run this command ` adb reverse tcp:9190 tcp:9190    python3 -m tvm.exec.query_rpc_tracker --host=0.0.0.0 --port=9190`
i see this 
`Tracker address 0.0.0.0:9190

Server List
------------------------------
server-address           key
------------------------------
       127.0.0.1:5001    server:android
------------------------------

Queue Status
-------------------------------
key       total  free  pending
-------------------------------
android   1      1     0
-------------------------------`

But when i run tune cmd 
i meet this for many hours:
`[Task qgemm_lut_t4_int8_m12288_k4096_n1_b3]  Current/Best:    0.00/   0.00 GFLOPS | Progress: (0/3) | 0.00 s'

**Comment by qw1319** [comment]
the question like this [https://discuss.tvm.apache.org/t/android-rpc-requesting-remote-session-from-rpc-tracker-failed/8413](url)

**Comment by qw1319** [comment]
> after run this command ` adb reverse tcp:9190 tcp:9190 python3 -m tvm.exec.query_rpc_tracker --host=0.0.0.0 --port=9190` i see this `Tracker address 0.0.0.0:9190
> 
> ## Server List
> ## server-address key
> ```
>    127.0.0.1:5001    server:android
> ```
> 
> ## Queue Status
> ## key total free pending
> android 1 1 0 -------------------------------`
> 
> But when i run tune cmd i meet this for many hours: `[Task qgemm_lut_t4_int8_m12288_k4096_n1_b3] Current/Best: 0.00/ 0.00 GFLOPS | Progress: (0/3) | 0.00 s'

and report error
InternalError: Check failed: (sock.Connect(addr)) is false: Connect to 127.0.0.1:5001 failed
