### ISSUE TITLE
The log is stuck on the "running build_py" line for 2 hours， is this normal?

### ISSUE THREAD

**Issue by sunj0104** [microsoft/T-MAC#56]
hello, I would like to consult you on a question. Thanks a lot. 

I run T-Mac on ubuntu. In order to speed the install speed, I use the command "pip install -e . -v -i https://pypi.tuna.tsinghua.edu.cn/simple", But, the log (running build_py) has been ongoing for 2 hours; no changes, is this normal?

Building wheels for collected packages: t-mac
  Running command Building editable for t-mac (pyproject.toml)
  running editable_wheel
  creating /tmp/pip-wheel-0oi5xt_5/.tmp-ozbv9npk/t_mac.egg-info
  writing /tmp/pip-wheel-0oi5xt_5/.tmp-ozbv9npk/t_mac.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-wheel-0oi5xt_5/.tmp-ozbv9npk/t_mac.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-wheel-0oi5xt_5/.tmp-ozbv9npk/t_mac.egg-info/requires.txt
  writing top-level names to /tmp/pip-wheel-0oi5xt_5/.tmp-ozbv9npk/t_mac.egg-info/top_level.txt
  writing manifest file '/tmp/pip-wheel-0oi5xt_5/.tmp-ozbv9npk/t_mac.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-wheel-0oi5xt_5/.tmp-ozbv9npk/t_mac.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-wheel-0oi5xt_5/.tmp-ozbv9npk/t_mac.egg-info/SOURCES.txt'
  creating '/tmp/pip-wheel-0oi5xt_5/.tmp-ozbv9npk/t_mac-1.0.0a3.dist-info'
  creating /tmp/pip-wheel-0oi5xt_5/.tmp-ozbv9npk/t_mac-1.0.0a3.dist-info/WHEEL
  running build_py

**Comment by sunj0104** [comment]
After i tried many times, I found too much time spent on downloading clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz, so I download clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz file manually, and put it on T-MAC/build/, then use the command tar -xJf clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz to unzip the file.  After that, when I use the command  "pip install -e . -v -i https://pypi.tuna.tsinghua.edu.cn/simple", the error occurred at the line “cmake ...”


(tmac) root@ubuntu:/home/ictuser/T-MAC/3rdparty/tvm/build# cmake ..
-- Forbidding undefined symbols in shared library, using -Wl,--no-undefined on platform Linux
-- Build with RPC support...
-- Build with Graph Executor support...
-- Build with profiler...
-- Build with AOT Executor support...
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Build Alloc alignment set to 64
-- Didn't find the path to CCACHE, disabling ccache
-- VTA build with VTA_HW_PATH=/home/ictuser/T-MAC/3rdparty/tvm/3rdparty/vta-hw
-- Build VTA runtime with target: sim
-- Use llvm-config=/home/ictuser/T-MAC/build/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/bin/llvm-config
/home/ictuser/T-MAC/build/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/bin/llvm-config: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/ictuser/T-MAC/build/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/bin/llvm-config)
/home/ictuser/T-MAC/build/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/bin/llvm-config: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/ictuser/T-MAC/build/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/bin/llvm-config)
/home/ictuser/T-MAC/build/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/bin/llvm-config: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/ictuser/T-MAC/build/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/bin/llvm-config)
/home/ictuser/T-MAC/build/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/bin/llvm-config: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/ictuser/T-MAC/build/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/bin/llvm-config)
CMake Error at cmake/utils/FindLLVM.cmake:80 (message):
  Fatal error executing:
  /home/ictuser/T-MAC/build/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/bin/llvm-config
  --libfiles
Call Stack (most recent call first):
  cmake/modules/LLVM.cmake:31 (find_llvm)
  CMakeLists.txt:559 (include)


-- Configuring incomplete, errors occurred!

**Comment by sunj0104** [comment]
Thanks very much, I fixed the promblem. But，when I use the command "pip install -e . -v -i https://pypi.tuna.tsinghua.edu.cn/simple", a new problem happen: 

 Consolidate compiler generated dependencies of target tvm_libinfo_objs
  [  0%] Performing configure step for 'project_libbacktrace'
  [  0%] Built target tvm_libinfo_objs
  /bin/sh: 1: /T-MAC/3rdparty/tvm/cmake/libs/../../3rdparty/libbacktrace/configure: not found
  make[2]: *** [CMakeFiles/project_libbacktrace.dir/build.make:131: libbacktrace/src/project_libbacktrace-stamp/project_libbacktrace-configure] Error 127
  make[1]: *** [CMakeFiles/Makefile2:229: CMakeFiles/project_libbacktrace.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  Consolidate compiler generated dependencies of target tvm_objs
  [ 91%] Built target tvm_objs
  make: *** [Makefile:136: all] Error 2
  Download and extraction completed successfully.
  running egg_info
  creating /tmp/tmpre3bcgei.build-temp/t_mac.egg-info
  writing /tmp/tmpre3bcgei.build-temp/t_mac.egg-info/PKG-INFO
  writing dependency_links to /tmp/tmpre3bcgei.build-temp/t_mac.egg-info/dependency_links.txt
  writing requirements to /tmp/tmpre3bcgei.build-temp/t_mac.egg-info/requires.txt
  writing top-level names to /tmp/tmpre3bcgei.build-temp/t_mac.egg-info/top_level.txt
  writing manifest file '/tmp/tmpre3bcgei.build-temp/t_mac.egg-info/SOURCES.txt'
  reading manifest file '/tmp/tmpre3bcgei.build-temp/t_mac.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  writing manifest file '/tmp/tmpre3bcgei.build-temp/t_mac.egg-info/SOURCES.txt'
  /tmp/pip-build-env-mhp_c6f4/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py:289: SetuptoolsDeprecationWarning: Customization incompatible with editable install
  !!

          ********************************************************************************
                          Traceback (most recent call last):
            File "<string>", line 119, in build_tvm
            File "/root/anaconda3/envs/t-mac/lib/python3.8/subprocess.py", line 364, in check_call
              raise CalledProcessError(retcode, cmd)
          subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2.

          The above exception was the direct cause of the following exception:

          Traceback (most recent call last):
            File "/tmp/pip-build-env-mhp_c6f4/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 295, in _safely_run
              return self.run_command(cmd_name)
            File "/tmp/pip-build-env-mhp_c6f4/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
              self.distribution.run_command(command)
            File "/tmp/pip-build-env-mhp_c6f4/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 950, in run_command
              super().run_command(command)
            File "/tmp/pip-build-env-mhp_c6f4/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
              cmd_obj.run()
            File "<string>", line 152, in run
            File "<string>", line 121, in build_tvm
          RuntimeError: Failed to build TVM


                          If you are seeing this warning it is very likely that a setuptools
                          plugin or customization overrides the `build_py` command, without
                          taking into consideration how editable installs run build steps
                          starting from setuptools v64.0.0.

                          Plugin authors and developers relying on custom build steps are
                          encouraged to update their `build_py` implementation considering the
                          information about editable installs in
                          https://setuptools.pypa.io/en/latest/userguide/extension.html.

                          For the time being `setuptools` will silence this error and ignore
                          the faulty command, but this behaviour will change in future versions.

          ********************************************************************************

  !!
    self._safely_run(name)

          Editable install will be performed using .pth file to extend `sys.path` with:
          ['python']

  Options like `package-data`, `include/exclude-package-data` or
  `packages.find.exclude/include` may have no effect.

**Comment by sunj0104** [comment]
deeply, when i use the command "make -j4", the error tell me /T-MAC/3rdparty/tvm/cmake/libs/../../3rdparty/libbacktrace/configure: not found, but it is exist really. 

 make -j4
[  0%] Performing configure step for 'project_libbacktrace'
[  0%] Building CXX object CMakeFiles/tvm_libinfo_objs.dir/src/support/libinfo.cc.o
/bin/sh: 1: /T-MAC/3rdparty/tvm/cmake/libs/../../3rdparty/libbacktrace/configure: not found
make[2]: *** [CMakeFiles/project_libbacktrace.dir/build.make:131: libbacktrace/src/project_libbacktrace-stamp/project_libbacktrace-configure] Error 127
make[1]: *** [CMakeFiles/Makefile2:229: CMakeFiles/project_libbacktrace.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by sammymx** [comment]
I met the problem  that got stuck here. Have you fixed this problem? I am downloading clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz file manually now as you mentioned.

**Comment by sunj0104** [comment]
thanks for the author of issue 42, who told me use TVM's GitHub repository to compile and ran T-MAC. It works.

**Comment by sunj0104** [comment]
> I met the problem that got stuck here. Have you fixed this problem? I am downloading clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz file manually now as you mentioned.

thanks for the author of issue 42, who told me use TVM's GitHub repository to compile and ran T-MAC, it works.

**Comment by sunj0104** [comment]
> [@sunj0104](https://github.com/sunj0104) Thanks for your info. We have been using fixed TVM commit 36b9535 (June 20) for some time, but we didn't meet your problem. Did you meet problem with this commit? And which TVM commit solved your problem?

After I pull the TVM’s repository (default commit and branch at that time )manually , I can run it successfully without any other issues.

**Comment by QingtaoLi1** [comment]
> > [@sunj0104](https://github.com/sunj0104) Thanks for your info. We have been using fixed TVM commit 36b9535 (June 20) for some time, but we didn't meet your problem. Did you meet problem with this commit? And which TVM commit solved your problem?
> 
> After I pull the TVM’s repository (default commit and branch at that time )manually , I can run it successfully without any other issues.

Do you remember the TVM commit ID you pulled?

**Comment by sunj0104** [comment]
> > > [@sunj0104](https://github.com/sunj0104) Thanks for your info. We have been using fixed TVM commit 36b9535 (June 20) for some time, but we didn't meet your problem. Did you meet problem with this commit? And which TVM commit solved your problem?
> > 
> > 
> > After I pull the TVM’s repository (default commit and branch at that time )manually , I can run it successfully without any other issues.
> 
> Do you remember the TVM commit ID you pulled?

Sorry, I don't remember the commit ID, but I remain the two tvm folders, do you know have any method I can get the commit ID?

**Comment by sunj0104** [comment]
hello,
I'm sorry to bother you, but I've run into a problem and need your help.  



as the issue I write on the github said, when I running "python tools/run_pipeline.py -o /root/QwenQwen2-7B-Instruct-GPTQ-Int4 -m gptq-auto -q int_n" report error like this:



......
INFO:hf-to-gguf:blk.27.attn_v.bias, torch.float16 --> F32, shape = {512}
INFO:hf-to-gguf:blk.27.attn_v.weight, torch.float16 --> I4, shape = {3584, 512}
INFO:hf-to-gguf:output_norm.weight, torch.float16 --> F32, shape = {3584}
Traceback (most recent call last):
File "convert_hf_to_gguf.py", line 4543, in
main()
File "convert_hf_to_gguf.py", line 4537, in main
model_instance.write()
File "convert_hf_to_gguf.py", line 527, in write
self.prepare_tensors()
File "convert_hf_to_gguf.py", line 352, in prepare_tensors
for name, data_torch in chain(self.generate_extra_tensors(), self.get_tensors()):
File "convert_hf_to_gguf.py", line 190, in get_tensors
raise ValueError("Mismatch between weight map and model parts for tensor names:\n"
ValueError: Mismatch between weight map and model parts for tensor names:
Missing tensors: []
Extra tensors: ['model.layers.0.mlp.down_proj.bias', 'model.layers.0.mlp.gate_proj.bias',......







Do you know the reason, thanks for your help~
